"""Add deployment_package_merges and framework_merges tables

Revision ID: 0001_add_tables
Revises: 4d32bca525b8
Create Date: 2026-08-09 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_add_tables"
down_revision: Union[str, Sequence[str], None] = "4d32bca525b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create deployment_package_merges table
    op.create_table(
        "deployment_package_merges",
        sa.Column("id", sa.VARCHAR(length=24), nullable=False),
        sa.Column("deploymentFrameworkId", sa.VARCHAR(length=24), nullable=False),
        sa.Column("packageVersion", sa.VARCHAR(length=20), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False, server_default="pending"),
        sa.Column("mergeKey", sa.VARCHAR(length=256), nullable=True),
        sa.Column("fileHashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="[]"),
        sa.Column("fileIds", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="[]"),
        sa.Column("mergeHistory", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="[]"),
        sa.Column("controls", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("deployment_package_merges_pkey")),
    )
    op.create_index(
        op.f("ix_deployment_package_merge_df_pkg"),
        "deployment_package_merges",
        ["deploymentFrameworkId", "packageVersion"],
        unique=True,
    )
    op.create_index(
        op.f("ix_deployment_package_merge_created"),
        "deployment_package_merges",
        ["createdAt"],
    )

    # Create framework_merges table
    op.create_table(
        "framework_merges",
        sa.Column("id", sa.VARCHAR(length=24), nullable=False),
        sa.Column("frameworkId", sa.VARCHAR(length=24), nullable=False),
        sa.Column("mergeKey", sa.VARCHAR(length=256), nullable=False),
        sa.Column("mergeHashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="[]"),
        sa.Column("fileVersions", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="[]"),
        sa.Column("controls", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("framework_merges_pkey")),
    )
    op.create_index(
        op.f("ix_framework_merge_fw_key"),
        "framework_merges",
        ["frameworkId", "mergeKey"],
        unique=True,
    )
    op.create_index(
        op.f("ix_framework_merge_created"),
        "framework_merges",
        ["createdAt"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f("ix_framework_merge_created"), table_name="framework_merges")
    op.drop_index(op.f("ix_framework_merge_fw_key"), table_name="framework_merges")
    op.drop_table("framework_merges")
    
    op.drop_index(op.f("ix_deployment_package_merge_created"), table_name="deployment_package_merges")
    op.drop_index(op.f("ix_deployment_package_merge_df_pkg"), table_name="deployment_package_merges")
    op.drop_table("deployment_package_merges")
    
    # ### end Alembic commands ###
