"""updated_tables

Revision ID: 4d32bca525b8
Revises: f36b540d5e5b
Create Date: 2026-08-07 12:38:40.015014

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4d32bca525b8"
down_revision: Union[str, Sequence[str], None] = "f36b540d5e5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_load_documents_tenant"), table_name="load_documents")
    op.drop_table("load_documents")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "load_documents",
        sa.Column("id", sa.VARCHAR(length=24), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("document_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("resource_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("file_hash", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("createdAt", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updatedAt", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("load_documents_pkey")),
    )
    op.create_index(op.f("ix_load_documents_tenant"), "load_documents", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
