"""update_framewrok_assignemt_table

Revision ID: 4feeeb66a776
Revises: c2baed3afb04
Create Date: 2026-08-10 12:38:59.365601

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4feeeb66a776"
down_revision: Union[str, Sequence[str], None] = "c2baed3afb04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
