"""Initial_migration

Revision ID: 79b2c5571e8f
Revises: 8831008e0a60
Create Date: 2026-08-10 16:17:57.957599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79b2c5571e8f'
down_revision: Union[str, Sequence[str], None] = '8831008e0a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_hash'), table_name='extraction_hash_registry')
    op.drop_table('extraction_hash_registry')
    op.drop_index(op.f('ix_agent_controls_control'), table_name='agent_controls')
    op.drop_table('agent_controls')
    op.drop_index(op.f('ix_extraction_results_ref'), table_name='extraction_results')
    op.drop_index(op.f('ix_extraction_results_resource'), table_name='extraction_results')
    op.drop_table('extraction_results')
    op.drop_index(op.f('ix_merge_hash'), table_name='merge_hash_registry')
    op.drop_table('merge_hash_registry')
    op.drop_table('agent_mappings')
    op.drop_index(op.f('ix_framework_merge_created'), table_name='framework_merges')
    op.drop_index(op.f('ix_framework_merge_fw_key'), table_name='framework_merges')
    op.create_index('ix_framework_merges_created', 'framework_merges', ['createdAt'], unique=False)
    op.create_index('ix_framework_merges_framework', 'framework_merges', ['frameworkId'], unique=False)
    op.create_index('ix_framework_merges_fw_merge_key', 'framework_merges', ['frameworkId', 'mergeKey'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_framework_merges_fw_merge_key', table_name='framework_merges')
    op.drop_index('ix_framework_merges_framework', table_name='framework_merges')
    op.drop_index('ix_framework_merges_created', table_name='framework_merges')
    op.create_index(op.f('ix_framework_merge_fw_key'), 'framework_merges', ['frameworkId', 'mergeKey'], unique=True)
    op.create_index(op.f('ix_framework_merge_created'), 'framework_merges', ['createdAt'], unique=False)
    op.create_table('agent_mappings',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_mappings_pkey'))
    )
    op.create_table('merge_hash_registry',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('hash_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('merge_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('merge_hash_registry_pkey'))
    )
    op.create_index(op.f('ix_merge_hash'), 'merge_hash_registry', ['hash_key'], unique=True)
    op.create_table('extraction_results',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('ref_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('package_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('extraction_results_pkey'))
    )
    op.create_index(op.f('ix_extraction_results_resource'), 'extraction_results', ['resource_type', 'ref_id'], unique=False)
    op.create_index(op.f('ix_extraction_results_ref'), 'extraction_results', ['ref_id'], unique=False)
    op.create_table('agent_controls',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('control_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_controls_pkey'))
    )
    op.create_index(op.f('ix_agent_controls_control'), 'agent_controls', ['control_id'], unique=False)
    op.create_table('extraction_hash_registry',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extraction_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('extraction_hash_registry_pkey'))
    )
    op.create_index(op.f('ix_extraction_hash'), 'extraction_hash_registry', ['file_hash'], unique=True)
    # ### end Alembic commands ###
