"""10-08-2027:4.13:PM

Revision ID: 837f3e37f9ec
Revises: aabd46f61d4a
Create Date: 2026-08-10 16:14:04.533022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837f3e37f9ec'
down_revision: Union[str, Sequence[str], None] = 'aabd46f61d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
