"""update_framework_table_and_docuemnt_extraction_table

Revision ID: 87d17e75605e
Revises: fd38baa01a43
Create Date: 2026-08-10 11:33:07.558884

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87d17e75605e"
down_revision: Union[str, Sequence[str], None] = "fd38baa01a43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
