"""Database_update

Revision ID: ddf978e9c462
Revises: 
Create Date: 2026-08-11 11:27:55.731535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddf978e9c462'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_threshold_config',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('implemented_threshold', sa.Float(), nullable=False),
    sa.Column('partially_implemented_threshold', sa.Float(), nullable=False),
    sa.Column('not_implemented_threshold', sa.Float(), nullable=False),
    sa.Column('implemented_label', sa.String(), nullable=False),
    sa.Column('partially_implemented_label', sa.String(), nullable=False),
    sa.Column('not_implemented_label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gap_threshold_unique', 'gap_threshold_config', ['is_active'], unique=True)
    op.drop_index(op.f('ix_gap_results_df'), table_name='deployment_gap_results')
    op.drop_table('deployment_gap_results')
    op.drop_index(op.f('ix_comparison_results_df'), table_name='comparison_results')
    op.drop_table('comparison_results')
    op.drop_index(op.f('ix_pkg_merge_track_df_ver'), table_name='package_merge_tracking')
    op.drop_table('package_merge_tracking')
    op.drop_index(op.f('ix_gap_config_key'), table_name='gap_config')
    op.drop_table('gap_config')
    op.drop_index(op.f('ix_gap_jobs_df'), table_name='deployment_gap_jobs')
    op.drop_table('deployment_gap_jobs')
    op.drop_index(op.f('ix_comparison_jobs_df'), table_name='comparison_jobs')
    op.drop_table('comparison_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_jobs',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('deployment_framework_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('package_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('framework_assignment_id', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('comparison_jobs_pkey'))
    )
    op.create_index(op.f('ix_comparison_jobs_df'), 'comparison_jobs', ['deployment_framework_id', 'package_version'], unique=False)
    op.create_table('deployment_gap_jobs',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('deployment_framework_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('package_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('deployment_gap_jobs_pkey'))
    )
    op.create_index(op.f('ix_gap_jobs_df'), 'deployment_gap_jobs', ['deployment_framework_id', 'package_version'], unique=False)
    op.create_table('gap_config',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('config_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('gap_config_pkey'))
    )
    op.create_index(op.f('ix_gap_config_key'), 'gap_config', ['config_key'], unique=True)
    op.create_table('package_merge_tracking',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('deployment_framework_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('package_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('package_merge_tracking_pkey'))
    )
    op.create_index(op.f('ix_pkg_merge_track_df_ver'), 'package_merge_tracking', ['deployment_framework_id', 'package_version'], unique=True)
    op.create_table('comparison_results',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('deployment_framework_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('package_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('comparison_results_pkey'))
    )
    op.create_index(op.f('ix_comparison_results_df'), 'comparison_results', ['deployment_framework_id', 'package_version'], unique=False)
    op.create_table('deployment_gap_results',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('deployment_framework_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('package_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('deployment_gap_results_pkey'))
    )
    op.create_index(op.f('ix_gap_results_df'), 'deployment_gap_results', ['deployment_framework_id', 'package_version'], unique=False)
    op.drop_index('ix_gap_threshold_unique', table_name='gap_threshold_config')
    op.drop_table('gap_threshold_config')
    # ### end Alembic commands ###
