"""Initial_migration

Revision ID: f36b540d5e5b
Revises: 
Create Date: 2026-08-04 18:45:15.737459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f36b540d5e5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_controls',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('control_id', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_controls_control', 'agent_controls', ['control_id'], unique=False)
    op.create_table('agent_mappings',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_prompts',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_jobs',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('deployment_framework_id', sa.String(length=24), nullable=False),
    sa.Column('package_version', sa.String(), nullable=False),
    sa.Column('framework_assignment_id', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comparison_jobs_df', 'comparison_jobs', ['deployment_framework_id', 'package_version'], unique=False)
    op.create_table('comparison_results',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('deployment_framework_id', sa.String(length=24), nullable=False),
    sa.Column('package_version', sa.String(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comparison_results_df', 'comparison_results', ['deployment_framework_id', 'package_version'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('secondaryPhone', sa.String(), nullable=True),
    sa.Column('isActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdBy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_active', 'customers', ['isActive'], unique=False)
    op.create_index('ix_customers_created', 'customers', ['createdAt'], unique=False)
    op.create_index('ix_customers_email', 'customers', ['email'], unique=True)
    op.create_index('ix_customers_tenant', 'customers', ['tenantId'], unique=True)
    op.create_table('deployment_documents',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=False),
    sa.Column('documentName', sa.String(), nullable=False),
    sa.Column('uploadedBy', sa.String(length=24), nullable=False),
    sa.Column('deploymentFrameworkId', sa.String(length=24), nullable=True),
    sa.Column('controlId', sa.String(), nullable=True),
    sa.Column('controlName', sa.String(), nullable=True),
    sa.Column('deploymentPoint', sa.String(), nullable=True),
    sa.Column('currentFileVersion', sa.String(), nullable=False),
    sa.Column('fileVersions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dd_tenant_created', 'deployment_documents', ['tenantId', 'createdAt'], unique=False)
    op.create_index('ix_dd_tenant_name', 'deployment_documents', ['tenantId', 'documentName'], unique=True)
    op.create_index('ix_dd_tenant_uploader', 'deployment_documents', ['tenantId', 'uploadedBy'], unique=False)
    op.create_table('deployment_frameworks',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=False),
    sa.Column('assignedFrameworkId', sa.String(length=24), nullable=False),
    sa.Column('frameworkId', sa.String(), nullable=True),
    sa.Column('frameworkName', sa.String(), nullable=False),
    sa.Column('frameworkCategoryId', sa.String(), nullable=True),
    sa.Column('frameworkCode', sa.String(), nullable=True),
    sa.Column('frameworkVersion', sa.String(), nullable=True),
    sa.Column('uploadedBy', sa.String(length=24), nullable=False),
    sa.Column('currentPackageVersion', sa.String(), nullable=False),
    sa.Column('packages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_df_tenant_category', 'deployment_frameworks', ['tenantId', 'frameworkCategoryId'], unique=False)
    op.create_index('ix_df_tenant_created', 'deployment_frameworks', ['tenantId', 'createdAt'], unique=False)
    op.create_index('ix_df_tenant_uploader', 'deployment_frameworks', ['tenantId', 'uploadedBy'], unique=False)
    op.create_table('deployment_gap_jobs',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('deployment_framework_id', sa.String(length=24), nullable=False),
    sa.Column('package_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gap_jobs_df', 'deployment_gap_jobs', ['deployment_framework_id', 'package_version'], unique=False)
    op.create_table('deployment_gap_results',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('deployment_framework_id', sa.String(length=24), nullable=False),
    sa.Column('package_version', sa.String(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gap_results_df', 'deployment_gap_results', ['deployment_framework_id', 'package_version'], unique=False)
    op.create_table('document_extractions',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('fileHash', sa.String(), nullable=False),
    sa.Column('aiExtraction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_extractions_hash', 'document_extractions', ['fileHash'], unique=True)
    op.create_table('evidence_output',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('control_id', sa.String(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_control', 'evidence_output', ['control_id'], unique=False)
    op.create_table('extraction_hash_registry',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('extraction_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extraction_hash', 'extraction_hash_registry', ['file_hash'], unique=True)
    op.create_table('extraction_results',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('ref_id', sa.String(length=24), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('package_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extraction_results_ref', 'extraction_results', ['ref_id'], unique=False)
    op.create_index('ix_extraction_results_resource', 'extraction_results', ['resource_type', 'ref_id'], unique=False)
    op.create_table('framework_assignments',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=False),
    sa.Column('customerId', sa.String(length=24), nullable=False),
    sa.Column('frameworkId', sa.String(length=24), nullable=False),
    sa.Column('frameworkCode', sa.String(), nullable=False),
    sa.Column('frameworkName', sa.String(), nullable=True),
    sa.Column('frameworkVersion', sa.String(), nullable=True),
    sa.Column('frameworkCategoryId', sa.String(), nullable=True),
    sa.Column('uploadedBy', sa.String(length=24), nullable=True),
    sa.Column('currentFileVersion', sa.String(), nullable=False),
    sa.Column('fileVersions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assignment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('finalization', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fa_tenant_customer_status', 'framework_assignments', ['tenantId', 'customerId', 'status'], unique=False)
    op.create_index('ix_fa_tenant_customer_ver', 'framework_assignments', ['tenantId', 'customerId', 'frameworkVersion'], unique=True)
    op.create_table('framework_categories',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('frameworkCategoryName', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('isActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('createdBy', sa.String(length=24), nullable=False),
    sa.Column('updatedBy', sa.String(length=24), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_framework_categories_active', 'framework_categories', ['isActive'], unique=False)
    op.create_index('ix_framework_categories_code', 'framework_categories', ['code'], unique=True)
    op.create_index('ix_framework_categories_created', 'framework_categories', ['createdAt'], unique=False)
    op.create_index('ix_framework_categories_created_by', 'framework_categories', ['createdBy'], unique=False)
    op.create_index('ix_framework_categories_updated_by', 'framework_categories', ['updatedBy'], unique=False)
    op.create_table('framework_category_access',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('expertId', sa.String(length=24), nullable=False),
    sa.Column('frameworkCategoryId', sa.String(length=24), nullable=False),
    sa.Column('frameworkCode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requestedBy', sa.String(), nullable=False),
    sa.Column('approval', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejection', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fca_code_status', 'framework_category_access', ['frameworkCode', 'status'], unique=False)
    op.create_index('ix_fca_created', 'framework_category_access', ['createdAt'], unique=False)
    op.create_index('ix_fca_expert_code', 'framework_category_access', ['expertId', 'frameworkCode'], unique=True)
    op.create_index('ix_fca_expert_status', 'framework_category_access', ['expertId', 'status'], unique=False)
    op.create_table('frameworks',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('frameworkName', sa.String(), nullable=False),
    sa.Column('frameworkVersion', sa.String(), nullable=False),
    sa.Column('frameworkCategoryId', sa.String(length=24), nullable=False),
    sa.Column('frameworkCode', sa.String(), nullable=False),
    sa.Column('uploadedBy', sa.String(length=24), nullable=False),
    sa.Column('currentFileVersion', sa.String(), nullable=False),
    sa.Column('fileVersions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_frameworks_created', 'frameworks', ['createdAt'], unique=False)
    op.create_index('ix_frameworks_uploaded_by', 'frameworks', ['uploadedBy'], unique=False)
    op.create_index('ix_frameworks_uploader_cat_ver', 'frameworks', ['uploadedBy', 'frameworkCategoryId', 'frameworkVersion'], unique=True)
    op.create_table('gap_config',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('config_key', sa.String(), nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gap_config_key', 'gap_config', ['config_key'], unique=True)
    op.create_table('load_documents',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_load_documents_tenant', 'load_documents', ['tenant_id'], unique=False)
    op.create_table('merge_hash_registry',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('hash_key', sa.String(), nullable=False),
    sa.Column('merge_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_merge_hash', 'merge_hash_registry', ['hash_key'], unique=True)
    op.create_table('package_comparisons',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('frameworkId', sa.String(length=24), nullable=False),
    sa.Column('fileHashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pkg_comp_framework', 'package_comparisons', ['frameworkId'], unique=False)
    op.create_table('package_gap_analyses',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('frameworkId', sa.String(length=24), nullable=False),
    sa.Column('fileHashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gapAnalysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pkg_gap_framework', 'package_gap_analyses', ['frameworkId'], unique=False)
    op.create_table('package_merge_tracking',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('deployment_framework_id', sa.String(length=24), nullable=False),
    sa.Column('package_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pkg_merge_track_df_ver', 'package_merge_tracking', ['deployment_framework_id', 'package_version'], unique=True)
    op.create_table('package_merges',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('frameworkId', sa.String(length=24), nullable=False),
    sa.Column('fileHashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sourceDocuments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mergeExtraction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pkg_merge_framework', 'package_merges', ['frameworkId'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('ref_id', sa.String(length=24), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('s3_url', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploaded_files_ref', 'uploaded_files', ['ref_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('secondaryPhone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('isEmailVerified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('isActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('otp', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokenVersion', sa.Integer(), server_default='0', nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdBy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_tenant_active', 'users', ['tenantId', 'isActive'], unique=False)
    op.create_index('ix_users_tenant_created', 'users', ['tenantId', 'createdAt'], unique=False)
    op.create_index('ix_users_tenant_email', 'users', ['tenantId', 'email'], unique=True)
    op.create_index('ix_users_tenant_phone', 'users', ['tenantId', 'phone'], unique=False)
    op.create_index('ix_users_tenant_role', 'users', ['tenantId', 'role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_tenant_role', table_name='users')
    op.drop_index('ix_users_tenant_phone', table_name='users')
    op.drop_index('ix_users_tenant_email', table_name='users')
    op.drop_index('ix_users_tenant_created', table_name='users')
    op.drop_index('ix_users_tenant_active', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_uploaded_files_ref', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('ix_pkg_merge_framework', table_name='package_merges')
    op.drop_table('package_merges')
    op.drop_index('ix_pkg_merge_track_df_ver', table_name='package_merge_tracking')
    op.drop_table('package_merge_tracking')
    op.drop_index('ix_pkg_gap_framework', table_name='package_gap_analyses')
    op.drop_table('package_gap_analyses')
    op.drop_index('ix_pkg_comp_framework', table_name='package_comparisons')
    op.drop_table('package_comparisons')
    op.drop_index('ix_merge_hash', table_name='merge_hash_registry')
    op.drop_table('merge_hash_registry')
    op.drop_index('ix_load_documents_tenant', table_name='load_documents')
    op.drop_table('load_documents')
    op.drop_index('ix_gap_config_key', table_name='gap_config')
    op.drop_table('gap_config')
    op.drop_index('ix_frameworks_uploader_cat_ver', table_name='frameworks')
    op.drop_index('ix_frameworks_uploaded_by', table_name='frameworks')
    op.drop_index('ix_frameworks_created', table_name='frameworks')
    op.drop_table('frameworks')
    op.drop_index('ix_fca_expert_status', table_name='framework_category_access')
    op.drop_index('ix_fca_expert_code', table_name='framework_category_access')
    op.drop_index('ix_fca_created', table_name='framework_category_access')
    op.drop_index('ix_fca_code_status', table_name='framework_category_access')
    op.drop_table('framework_category_access')
    op.drop_index('ix_framework_categories_updated_by', table_name='framework_categories')
    op.drop_index('ix_framework_categories_created_by', table_name='framework_categories')
    op.drop_index('ix_framework_categories_created', table_name='framework_categories')
    op.drop_index('ix_framework_categories_code', table_name='framework_categories')
    op.drop_index('ix_framework_categories_active', table_name='framework_categories')
    op.drop_table('framework_categories')
    op.drop_index('ix_fa_tenant_customer_ver', table_name='framework_assignments')
    op.drop_index('ix_fa_tenant_customer_status', table_name='framework_assignments')
    op.drop_table('framework_assignments')
    op.drop_index('ix_extraction_results_resource', table_name='extraction_results')
    op.drop_index('ix_extraction_results_ref', table_name='extraction_results')
    op.drop_table('extraction_results')
    op.drop_index('ix_extraction_hash', table_name='extraction_hash_registry')
    op.drop_table('extraction_hash_registry')
    op.drop_index('ix_evidence_control', table_name='evidence_output')
    op.drop_table('evidence_output')
    op.drop_index('ix_doc_extractions_hash', table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_index('ix_gap_results_df', table_name='deployment_gap_results')
    op.drop_table('deployment_gap_results')
    op.drop_index('ix_gap_jobs_df', table_name='deployment_gap_jobs')
    op.drop_table('deployment_gap_jobs')
    op.drop_index('ix_df_tenant_uploader', table_name='deployment_frameworks')
    op.drop_index('ix_df_tenant_created', table_name='deployment_frameworks')
    op.drop_index('ix_df_tenant_category', table_name='deployment_frameworks')
    op.drop_table('deployment_frameworks')
    op.drop_index('ix_dd_tenant_uploader', table_name='deployment_documents')
    op.drop_index('ix_dd_tenant_name', table_name='deployment_documents')
    op.drop_index('ix_dd_tenant_created', table_name='deployment_documents')
    op.drop_table('deployment_documents')
    op.drop_index('ix_customers_tenant', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_index('ix_customers_created', table_name='customers')
    op.drop_index('ix_customers_active', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_comparison_results_df', table_name='comparison_results')
    op.drop_table('comparison_results')
    op.drop_index('ix_comparison_jobs_df', table_name='comparison_jobs')
    op.drop_table('comparison_jobs')
    op.drop_table('agent_prompts')
    op.drop_table('agent_mappings')
    op.drop_index('ix_agent_controls_control', table_name='agent_controls')
    op.drop_table('agent_controls')
    # ### end Alembic commands ###
