"""Add GapThresholdConfig table

Revision ID: f50407db0c27
Revises: ae30355a38a6
Create Date: 2026-08-11 01:18:05.730695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50407db0c27'
down_revision: Union[str, Sequence[str], None] = 'ae30355a38a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_threshold_config',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('implemented_threshold', sa.Float(), nullable=False),
    sa.Column('partially_implemented_threshold', sa.Float(), nullable=False),
    sa.Column('not_implemented_threshold', sa.Float(), nullable=False),
    sa.Column('implemented_label', sa.String(), nullable=False),
    sa.Column('partially_implemented_label', sa.String(), nullable=False),
    sa.Column('not_implemented_label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gap_threshold_unique', 'gap_threshold_config', ['is_active'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gap_threshold_unique', table_name='gap_threshold_config')
    op.drop_table('gap_threshold_config')
    # ### end Alembic commands ###
