"""update_framework_table_and_document_extraction_table

Revision ID: fd38baa01a43
Revises: 8ae65b5a8195
Create Date: 2026-08-10 11:25:43.171190

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd38baa01a43"
down_revision: Union[str, Sequence[str], None] = "8ae65b5a8195"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
